export const chatList = [
  {
    id: 1,
    profileImg: 'http://chatvia-dark.react.themesbrand.com/static/media/avatar-2.feb0f89de58f0ef9b424.jpg',
    name: 'Patrick Hendricks',
    lastMessage: 'okay sure',
    time: '2:50',
    unread: 2,
    status: 'online',
  },
  {
    id: 2,
    profileImg: 'http://chatvia-dark.react.themesbrand.com/static/media/avatar-3.2cfd5ba6f0dee8d1d076.jpg',
    name: 'Mark Messer',
    lastMessage: 'okay sure',
    time: '12:50',
    status: 'away',
  },
  {
    id: 2,
    profileImg: 'http://chatvia-dark.react.themesbrand.com/static/media/avatar-3.2cfd5ba6f0dee8d1d076.jpg',
    name: 'Mark Messer',
    lastMessage: 'okay sure',
    time: '12:50',
    status: 'away',
  },
  {
    id: 2,
    profileImg: 'http://chatvia-dark.react.themesbrand.com/static/media/avatar-3.2cfd5ba6f0dee8d1d076.jpg',
    name: 'Mark Messer',
    lastMessage: 'okay sure',
    time: '12:50',
    status: 'away',
  },
  {
    id: 2,
    profileImg: 'http://chatvia-dark.react.themesbrand.com/static/media/avatar-3.2cfd5ba6f0dee8d1d076.jpg',
    name: 'Mark Messer',
    lastMessage: 'okay sure',
    time: '12:50',
    status: 'away',
  },
  {
    id: 2,
    profileImg: 'http://chatvia-dark.react.themesbrand.com/static/media/avatar-3.2cfd5ba6f0dee8d1d076.jpg',
    name: 'Mark Messer',
    lastMessage: 'okay sure',
    time: '12:50',
    status: 'away',
  },
  {
    id: 2,
    profileImg: 'http://chatvia-dark.react.themesbrand.com/static/media/avatar-3.2cfd5ba6f0dee8d1d076.jpg',
    name: 'Mark Messer',
    lastMessage: 'okay sure',
    time: '12:50',
    status: 'away',
  },
  {
    id: 2,
    profileImg: 'http://chatvia-dark.react.themesbrand.com/static/media/avatar-3.2cfd5ba6f0dee8d1d076.jpg',
    name: 'Mark Messer',
    lastMessage: 'okay sure',
    time: '12:50',
    status: 'away',
  },
  {
    id: 2,
    profileImg: 'http://chatvia-dark.react.themesbrand.com/static/media/avatar-3.2cfd5ba6f0dee8d1d076.jpg',
    name: 'Mark Messer',
    lastMessage: 'okay sure',
    time: '12:50',
    status: 'away',
  },
];
